---
abstract: 'Oracle ZFS Storage Appliance RESTful API Connector'
author:
  - 'Wesley Hinds <wesley.hinds@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Oracle-ZFSSA-Client
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: '6.05'
  JSON: '2.90'
  perl: '5.006'
resources:
  repository: https://github.com/whindsx/Oracle-ZFSSA-Client 
version: '0.01'
